filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - test_data/glog.log
    fields:
      source: glog

#==================== Elasticsearch template setting ==========================
setup.template.settings:
  index.number_of_shards: 1
  #index.codec: best_compression
  #_source.enabled: false
#============================== Kibana =====================================

# Starting with Beats version 6.0.0, the dashboards are loaded via the Kibana API.
# This requires a Kibana endpoint configuration.
setup.kibana:
  host: "127.0.0.1:5601"
#-------------------------- Elasticsearch output ------------------------------
setup.template.name: "customname"
setup.template.pattern: "customname-*"

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["127.0.0.1:9200"]
  #index: "customname-%{[agent.version]}-%{+yyyy.MM.dd}"
  indices:
    - index: glog-%{+yyyy.MM.dd}
  #protocol: "https"
  #username: "elastic"
  #password: ""


# Configure processors to enhance or manipulate events generated by the beat.
processors:
  - drop_fields:
      fields: ["@timestamp","@metadata","metadata","timestamp","fields","agent","ecs","input","log","host"]
  - script:
        lang: javascript
        file: ${path.config}/script_format1.js
